# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'a986a08dd5650b123d043b48549c7202'
  config.secret_key = 'bc77a15c346a684638f359a774b332cc'
  config.default_from = 'boivin.remi@outlook.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
