# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Rails workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rails-workflow:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 3.0.1
      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: rspec spec/

      - name: Run braekman
        run: |
          brakeman -q -w2

      - name: Run linters
        run: |
          rubocop --parallel
